# Linear Algebra Using Numpy

## Table of contents
- [Import Package](#1)
- [Numpy](#2)
    - [1-D Array](#2-1)
    - [2-D, 3-D Arrays](#2-2)
    - [Other ways to initialize a numpy array](#2-3)
- [Linear Algebra in Numpy](#3)
  - [Element-wise operations](#3-1)
  - [Broadcasting](#3-2)
  - [Matrix Multiplication](#3-3)
  - [Transpose](#3-4)
  - [Dot Product](#3-5)
- [L1 and L2 Norms](#4)
  - [L1 Norm  (Manhattan Norm)](#4-1)
  - [L2 Norm (Euclidean Norm)](#4-2)
- [Comparison between Standard Python and Numpy](#5)

<a name='1'></a>
## Import Packages

In [2]:
# Import Numpy
import numpy as np

<a name='2'></a>
## Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### Numpy Arrays (Matricies and Vectors)

<a name='2-1'></a>
**1-D Array**

In [3]:
one_d_vec = np.array([5, -1, 1, 0.2, 4.1, 3.5, 12.0, -6.3])
print('one_d_vec', one_d_vec)
int_vec= np.array([5, -1, 1, 0.2, 4.1, 3.5, 12.0, -6.3], dtype=int)
print('int_vec', int_vec)
str_vector = np.array([5, -1, 1, 0.2, 4.1, 3.5, 12.0, -6.3], dtype=str)
print('str_vector', str_vector)

one_d_vec [ 5.  -1.   1.   0.2  4.1  3.5 12.  -6.3]
int_vec [ 5 -1  1  0  4  3 12 -6]
str_vector ['5' '-1' '1' '0.2' '4.1' '3.5' '12.0' '-6.3']


<a name='2-2'></a>
**2-D Arrays**

In [ ]:
two_d_array = np.array([[5, -1, 1, 0],[4, 3, 12, -6]])
print(f'This is a 2D array of shape {two_d_array.shape}\n', two_d_array)

<table style="background-color: white; color: black;">
<tr>
  <th>A scalar, shape: <code>[]</code></th>
  <th>A vector, shape: <code>[3]</code></th>
  <th>A matrix, shape: <code>[3, 2]</code></th>
</tr>
<tr>
  <td>
   <img src="images/scalar.png" alt="A scalar, the number 4" />
  </td>

  <td>
   <img src="images/vector.png" alt="The line with 3 sections, each one containing a number."/>
  </td>
  <td>
   <img src="images/matrix.png" alt="A 3x2 grid, with each cell containing a number.">
  </td>
</tr>
</table>

The tensor above has a shape `(3,2)` which means our matrix has 3 rows and 2 columns. 

**3-D Arrays**

In [ ]:
three_d_array = np.array([[[1, 2, 3], [4, 5, 6]],
                          [[7, 8, 9], [10, 11, 12]],
                          [[13, 14, 15], [16, 17, 18]]])
print(f"\nThis is a 3D array of shape {three_d_array.shape}\n", three_d_array)

<table style="background-color: white; color: black;">
<tr>
  <th colspan=3>A 3-axis tensor, shape: <code>[3, 2, 5]</code></th>
<tr>
<tr>
  <td>
   <img src="images/3-axis_numpy.png"/>
  </td>
  <td>
   <img src="images/3-axis_front.png"/>
  </td>

  <td>
   <img src="images/3-axis_block.png"/>
  </td>
</tr>

</table>

<a name='2-3'></a>
**Other ways to initialize a numpy array**
1. **Zeros or Ones**: Create arrays filled with zeros or ones
2. **Empty**: Create an uninitialized array
3. **Arange**: Create an array with regularly spaced values
4. **Linspace**: Create an array with a specified number of evenly spaced values
5. **Random**: Create an array with random values
6. **Eye**: Create an identity matrix
7. **Diag**: Create a diagonal matrix
8. **From Function**: Create an array based on a function (very rarely used)

In [5]:
# Zeros
zeros_arr = np.zeros((3, 4))  # 3x4 array of zeros
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Ones
ones_arr = np.ones((2, 2))    # 2x2 array of ones
print(ones_arr)

[[1. 1.]
 [1. 1.]]


In [7]:
# Empty
empty_arr = np.empty((2, 3))
print(empty_arr)

[[1.1997618e-311 1.1997618e-311 1.1997618e-311]
 [1.1997618e-311 1.1997618e-311 1.1997618e-311]]


In [8]:
# Arange
range_arr = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print(range_arr)

[0 2 4 6 8]


In [9]:
# Linspace
linspace_arr = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
# Random
random_arr = np.random.rand(3, 2)  # 3x2 array with random values in [0, 1)
print(random_arr)

[[0.90835412 0.83416544]
 [0.84722186 0.22247775]
 [0.18988865 0.80515397]]


In [11]:
# Eye
identity_mat = np.eye(3)  # 3x3 identity matrix
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Diag
diagonal_mat = np.diag([1, 2, 3])  # Diagonal matrix with specified values
print(diagonal_mat)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
# From Function
func_arr = np.fromfunction(lambda i, j: i + j, (3, 3))  # 3x3 array using a function
print(func_arr)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


<a name='3'></a>
## Linear Algebra in Numpy

### Operations on Matrices

<a name='3-1'></a>
#### Element-wise operations

Suppose A, B, and C are 2-D matrices

Element-wise addition and multiplication in NumPy refer to performing addition and multiplication operations on corresponding elements of two arrays.

**Addition**:

When two matrices have the same shape, they can be added by summing up each of their corresponding entries together.

$$(A + C)_{ij} = a_{ij} + c_{ij}$$

<img src="images/vector_addition.png" width="600px"/>

<table style="background-color: white; color: black;">
<tr>
  <th>Sum of vectors</th>
  <th>Difference of vectors</th>
</tr>
<tr>
  <td>
   <img src="images/sum_of_vectors.png" width="300px"/>
  </td>

  <td>
   <img src="images/difference_of_vectors.png" width="300px"/>
  </td>
</tr>
</table>

**Multiplication**:

1. Multiplying matrix with a scalar:
   
Multiplying a matrix of any shape by a scalar involves multiplying each entry of the matrix by that scalar. We can express it using subscript notation:

$$(cA)_{ij} = c \cdot a_{ij}$$

<img src="images/scalar_x_vector.png" width="300px"/>

2. Multiplying two matrices element-wise:

Element-wise multiplication of two matrices involves multiplying corresponding elements of the matrices together. If you have two matrices $A$ and $B$ of the same shape (both $m \times n$), the element-wise multiplication is denoted as C=A⊙B, where C is the resulting matrix.

$$C_{ij} = A_{ij} \odot B_{ij}$$
$$c_{ij} = a_{ij} \times b_{ij}$$


In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Element-wise addition with scalar
result_addition = matrix + 10
print("The result of adding a scalar to an array\n", result_addition)

print('**************')

# Element-wise multiplication with scalar
result_multiplication = matrix * 2
print("The result of multiplying a matrix with a scalar\n", result_multiplication)


print('**************')

# Element-wise addition with matrix
result_addition = matrix + matrix
print("The result of element-wise addition of 2 matrices\n", result_addition)

print('**************')

# Element-wise multiplication
result_multiplication = matrix * matrix
print("The result of elemetn-wise multiplication of 2 arrays\n", result_multiplication)

The result of adding a scalar to an array
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
**************
The result of multiplying a matrix with a scalar
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
**************
The result of element-wise addition of 2 matrices
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
**************
The result of elemetn-wise multiplication of 2 arrays
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


<a name='3-2'></a>
**Broadcasting**:

NumPy automatically performs these operations element-wise when the arrays have compatible shapes for broadcasting. Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes and sizes.

A      (2d array):  5 x 4 \
B      (1d array):      1 \
Result (2d array):  5 x 4

A      (2d array):  5 x 4 \
B      (1d array):      4 \
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5 \
B      (3d array):  15 x 1 x 5 \
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5 \
B      (2d array):       3 x 5 \
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5 \
B      (2d array):       3 x 1 \
Result (3d array):  15 x 3 x 5

In [15]:
matrix_2 = np.array([1, 2, 3])
result_multiplicaiton_broadcast = matrix * matrix_2
print("The result of elemetn-wise multiplication of 2 arrays\n", result_multiplicaiton_broadcast)
print('*********************')

matrix_3 = np.array([[1], [2], [3]])
result_multiplicaiton_broadcast2 = matrix * matrix_3
print("The result of elemetn-wise multiplication of 2 arrays\n", result_multiplicaiton_broadcast2)
print('*********************')

result_multiplicaiton_broadcast3 = matrix_2 * matrix_3
print("The result of elemetn-wise multiplication of 2 arrays\n", result_multiplicaiton_broadcast3)
print('*********************')


The result of elemetn-wise multiplication of 2 arrays
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
*********************
The result of elemetn-wise multiplication of 2 arrays
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
*********************
The result of elemetn-wise multiplication of 2 arrays
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
*********************


<a name='3-5'></a>
#### Dot Product

For vectors $ \mathbf{U} $ and $ \mathbf{V} $ in $\mathbb{R}^n$, the dot product is written as $ \mathbf{U} \cdot \mathbf{V} $, and is defined as follows:

$$ \mathbf{U} \cdot \mathbf{V} = U_1 \cdot V_1 + U_2 \cdot V_2 + \ldots + U_n \cdot V_n $$

The result of dot product for 2 vectors is a scalar which can be observed from the equation.

$$
A = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}, \quad
B = \begin{bmatrix} 4 & 5 & 6 \end{bmatrix}
$$

$$ A \cdot B = 1\cdot4 + 2\cdot5 + 3\cdot6 = 32 $$

Dot product is a shortcut for linear operations

<img src="images/dot_product_shortcut.png" height="300px"/>

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

result = np.dot(A, B)

print("Dot product result",result)


<a name='3-4'></a>
#### Transpose

Another important concept is the matrix transpose. When we transpose a matrix $A$, denoted as $A^{T}$, we essentially flip its rows and columns. To get the elements of $A^{T}$, we swap the row index with the column index for each entry. In simpler terms, if $A$ has an element $a_{ij}$, then in $A^{T}$ this element becomes $a_{ji}$. This operation transforms the columns of $A$ into the rows of $A_{T}$
 
Suppose you have the matrix:
$$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix} $$

The transpose of $A$, denoted as $A^T$
$$ A^T = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix} $$


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_transpose = np.transpose(A)
# Alternatively, you can use A.T

print("Matrix A:")
print(A)

print("\nTranspose of A:")
print(A_transpose)

<a name='3-3'></a>
#### Matrix Multiplication

To multiply a matrix $A$ of size $(n \times m)$ with matrix $B$, $B$ should have $m$ rows; so that the size of matrix $B$ should be $(m\times k)$. Where n, m, k being any natural number.

The resulting matrix, denoted as $AB$, will have the same number of rows as $A$ and the same number of columns as $B$. In other words, if $A$ is of shape ($n \times m$) and $B$ is of shape ($m \times k$), then we can multiply them and the resulting matrix $AB$ will be of shape ($n \times k$) $$ AB_{n \times k} = A_{n \times m} \times B_{m \times k} $$

Note that in this case, multiplying $BA$ since the dimensions are not compatible; i.e, column $k$ of matrix $B$ is not equal to the number of rows $n$ of matrix $A$. BE CAREFUL TO THE ORDER!!!

Example:

$$ A = \begin{bmatrix} a_1 & a_2 & a_3 \\ a_4 & a_5 & a_6 \end{bmatrix} = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} $$
$$ B = \begin{bmatrix} b_1 & b_2 \\ b_3 & b_4 \\ b_5 & b_6 \end{bmatrix} = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix} $$
$$ C = A \times B  = \begin{bmatrix} c_1 & c_2 \\ c_3 & c_4 \end{bmatrix} = \begin{bmatrix} 58 & 64 \\ 139 & 154 \end{bmatrix} $$

Where:
$$ c_1 = a_1 \times b_1 + a_2 \times b_3 + a_3 \times b_5 $$
$$ c_2 = a_1 \times b_2 + a_2 \times b_4 + a_3 \times b_6 $$
$$ c_3 = a_4 \times b_1 + a_5 \times b_3 + a_6 \times b_5 $$
$$ c_4 = a_4 \times b_2 + a_5 \times b_4 + a_6 \times b_6 $$




In [16]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

result_matrix_multiplication = matrix_a @ matrix_b
print('Result of matrix Multiplication\n', result_matrix_multiplication)

Result of matrix Multiplication
 [[ 58  64]
 [139 154]]


In Numpy, using **dot product** for 2D matrices is the same as matrix multiplication. However, for multidimensional matrices, the results differ

In [19]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

result_matrix_multiplication = matrix_a @ matrix_b
result_matrix_dot_2d = np.dot(matrix_a, matrix_b)
print('Result of matrix Multiplication\n', result_matrix_multiplication)
print('Result of dot product of 2D matrices\n', result_matrix_dot_2d)
print('\n*****************\n')


tensor_a = np.random.rand(3, 4, 5)
tensor_b = np.random.rand(3, 5, 2)

result_dot_tensor = np.dot(tensor_a, tensor_b)
print("Size of the result of dot product of N-D matrices",result_dot_tensor.shape)
result_matmul_tensor = np.matmul(tensor_a, tensor_b)
print("Size of the result of multiplication of N-D matrices", result_matmul_tensor.shape)

Result of matrix Multiplication
 [[ 58  64]
 [139 154]]
Result of dot product of 2D matrices
 [[ 58  64]
 [139 154]]

*****************

Size of the result of dot product of N-D matrices (3, 4, 3, 2)
Size of the result of multiplication of N-D matrices (3, 4, 2)


In [20]:
%%timeit
np.dot(matrix_a, matrix_b)

1.1 µs ± 35.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
%%timeit
np.matmul(matrix_a, matrix_b)

1.4 µs ± 28.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


<a name='4'></a>
## L1 and L2 Norms

<a name='4-1'></a>
### L1 Norm  (Manhattan Norm):

The L1 norm of a vector $x$, denoted as $∥x∥_1$, is the sum of the absolute values of its elements. Mathematically, it is defined as:

$$ ||\mathbf{x}\|_1 = \sum_{i=1}^{n} |x_i| $$

Here:
- $x$ is the vector.
- $n$ is the number of elements in the vector.
- $∣x_i∣$ denotes the absolute value of the $i-th$ element.
  
The L1 norm corresponds to the "Manhattan distance" between the origin (or any point) and the point defined by the vector. 

In [22]:
x = np.array([1, -2, 3, -4, 5])

# L1 Norm
l1_norm = np.linalg.norm(x, ord=1)
print("L1 Norm:", l1_norm)

L1 Norm: 15.0


<a name='4-2'></a>
### L2 Norm (Euclidean Norm):

he L2 norm of a vector $x$, denoted as $∥x∥_2$, is the square root of the sum of the squared values of its elements. Mathematically, it is defined as:

$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^{n} x_i^2}$$

Here:

- $x$ is the vector.
- $n$ is the number of elements in the vector.
- $x_{i}^{2}$ denotes the square of the $i-th$ element.
  
The L2 norm corresponds to the "Euclidean distance" between the origin (or any point) and the point defined by the vector. It is the straight-line distance between two points in Euclidean space.


In [23]:
# L2 Norm
l2_norm = np.linalg.norm(x, ord=2)
print("L2 Norm:", l2_norm)

L2 Norm: 7.416198487095663


<a name='4-3'></a>
### Applications in Machine Learning:

**L1 Norm:**

- Used in regularization techniques (L1 regularization or Lasso) to promote sparsity in models by encouraging some weights to become exactly zero.
- Feature selection, where it helps in creating sparse solutions. (a sparse solution refers to a solution where many of the coefficients or parameters associated with features are exactly zero.)

**L2 Norm:**

- Commonly used in optimization problems, including linear regression and support vector machines.
- Regularization techniques (L2 regularization or Ridge) to prevent overfitting and control the magnitude of weights.

<a name='5'></a>
## Comparison between Standard Python and Numpy

In [24]:
import random

rows, cols = 1000, 1000

random_list = [[random.randint(1, 10) for _ in range(cols)] for _ in range(rows)]

numpy_array_a = np.array(random_list)

def multiply_python_matrices(a, b):
    result = [[0 for _ in range(cols)] for _ in range(rows)]
    for i in range(rows):
        for j in range(cols):
            result[i][j] = a[i][j] * b[i][j]
    return result

import time

start_time_numpy = time.time()
numpy_result = numpy_array_a * numpy_array_a
end_time_numpy = time.time()
numpy_execution_time = end_time_numpy - start_time_numpy

start_time_python = time.time()
python_result = multiply_python_matrices(random_list, random_list)
end_time_python = time.time()
python_execution_time = end_time_python - start_time_python

speedup = python_execution_time / numpy_execution_time

print("\nExecution Time Comparison:")
print("NumPy Execution Time:", numpy_execution_time)
print("Standard Python Execution Time:", python_execution_time)
print("Speed up:", speedup, "times faster")



Execution Time Comparison:
NumPy Execution Time: 0.0017249584197998047
Standard Python Execution Time: 0.12271308898925781
Speed up: 71.13973738769869 times faster


In [25]:
%%timeit -n100
python_result = multiply_python_matrices(random_list, random_list)

118 ms ± 1.74 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%%timeit -n100
numpy_result = numpy_array_a * numpy_array_a

1.6 ms ± 30.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
